# Site settings
title: janelee.org
description: > # this means to ignore newlines until "baseurl:"
  Thoughts, explorations, etc.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.janelee.org" # the base hostname & protocol for your site
twitter_username: ramblingjane
github_username:  ramblingjane

# Build settings
markdown: kramdown

future: true